services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tor-online-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    container_name: tor-online-ws
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT_WS=3001
      - HOST=0.0.0.0
